### PR TITLE
Add "rmarkdown" to dependencies, etc.

### PR DESCRIPTION
**Pull request by GegznaV**
Add "rmarkdown" to suggested dependencies and other minor improvements related to vignettes.

### CODE REVIEW

**Comment by GegznaV** [comment]
I created the commits with `[!!!]` to show where the issues lie. These must be carefully reviewed after PR is accepted.

**Comment by GegznaV** [comment]
There are some typos in the commit messages. Should be, e.g., temporary, added. Sorry about that.

**Review by cbeleites — APPROVED** [review]

**Comment by cbeleites** [comment]
I "forced" the merge - was still waiting for some Travis results. Let's see what happens...

**Comment by GegznaV** [comment]
> was still waiting for some Travis results. Let's see what happens...

It could take an eternity before the status changes. It is a known issue. See #22.

**Pull request merged**
